### ISSUE TITLE
Starting 'scale' error

### ISSUE THREAD

**Issue by gageoleighton** [chaeron/thermostat#2]
The first time I started the code it launched everything just fine, showed a temp of 22C but now whenever I try to start the code it gives the error:
`pi@raspberrypi:~ $ sudo python Downloads/thermostat-master/thermostat.py
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_17-04-20_5.txt
[INFO   ] [Kivy        ] v1.9.2.dev0, git-e831904, 20170420
[INFO   ] [Python      ] v2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "Downloads/thermostat-master/thermostat.py", line 380, in <module>
     tempScale		  = settings.get( "scale" )[ "tempScale" ]
   File "/usr/local/lib/python2.7/dist-packages/kivy/storage/__init__.py", line 159, in get
     return self.store_get(key)
   File "/usr/local/lib/python2.7/dist-packages/kivy/storage/jsonstore.py", line 50, in store_get
     return self._data[key]
 KeyError: 'scale'`

This is a brand new Pi 3 and AM2302, should I go about starting installation again or do you know what is causing this error?

**Comment by gageoleighton** [comment]
Apologies, I was simply running the wrong script and the sensor I had wasn't working. Using a BMP180 while I wait for another sensor in the mail.

:P
